import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';

const GLYPHS = {
  'chevron.left': 'chevron-left',
  'chevron.right': 'chevron-right',
  'chevron.up': 'chevron-up',
  'chevron.down': 'chevron-down',
  magnifyingglass: 'magnify',
  plus: 'plus',
  minus: 'minus',
  xmark: 'close',
  'xmark.circle.fill': 'close-circle',
  checkmark: 'check',
  'checkmark.circle.fill': 'check-circle',
  'square.grid.2x2': 'view-grid-outline',
  'doc.on.doc': 'content-copy',
  cart: 'cart-outline',
  pencil: 'pencil-outline',
  trash: 'trash-can-outline',
  'bag.fill': 'shopping-outline',
  'clock.fill': 'clock-outline',
  scope: 'target',
  'chart.line.uptrend.xyaxis': 'chart-line',
  'person.2.fill': 'account-group-outline',
  'line.3.horizontal.decrease': 'filter-variant',
  'shippingbox.fill': 'package-variant-closed',
  'cube.box.fill': 'cube-outline',
  eye: 'eye-outline',
  'eye.slash': 'eye-off-outline',
  ellipsis: 'dots-horizontal',
  'sun.max.fill': 'white-balance-sunny',
  'moon.fill': 'moon-waning-crescent',
  'tray.and.arrow.down': 'content-save-outline',
  creditcard: 'credit-card-outline',
  'tag.fill': 'tag-outline',
  map: 'map-outline',
  clipboard: 'clipboard-text-outline',
  'person.badge.plus': 'account-plus-outline',
  cash: 'cash-multiple',
  sync: 'sync',
  'shippingbox.slash': 'package-variant-remove',
  lifebuoy: 'lifebuoy',
  'wifi.slash': 'wifi-off',
  'person.crop.circle': 'account-circle',
  gearshape: 'cog-outline',
  whatsapp: 'whatsapp',
  'phone.fill': 'phone',
  smartphone: 'cellphone',
  'list.bullet': 'format-list-bulleted',
  mappin: 'map-marker',
  store: 'store-outline',
  'mappin.slash': 'map-marker-off',
  'person.fill': 'account',
  polygon: 'vector-polygon',
  'square.dashed': 'vector-square',
  route: 'map-marker-path',
  'hand.tap': 'gesture-tap',
  'figure.walk': 'walk',
  'car.fill': 'car-outline',
  'moto.fill': 'motorbike',
  camera: 'camera-outline',
  'doc.text': 'text-box-outline',
  checklist: 'format-list-checks',
  star: 'star-outline',
  'star.fill': 'star',
  'flag.fill': 'flag-variant',
  calendar: 'calendar-outline',
  'exclamationmark.circle': 'alert-circle-outline',
  photo: 'image-outline',
  'folder.fill': 'folder-image',
  'door.exit': 'exit-run',
} as const;

export type IconName = keyof typeof GLYPHS;

export function Icon({ name, size = 16, color }: { name: IconName; size?: number; color: string }) {
  return <MaterialCommunityIcons name={GLYPHS[name]} size={size} color={color} />;
}
